# Generated by Django 4.1.5 on 2023-05-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firewallrule',
            old_name='name',
            new_name='rule_name',
        ),
        migrations.RemoveField(
            model_name='firewallrule',
            name='action',
        ),
        migrations.RemoveField(
            model_name='firewallrule',
            name='rule',
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='alert_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='direction',
            field=models.CharField(default='incoming', max_length=100),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='log_traffic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='port_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='protocol_type',
            field=models.CharField(default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='traffic_type',
            field=models.CharField(default='any', max_length=20),
        ),
    ]
