# Generated by Django 4.1.5 on 2023-05-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_rename_name_firewallrule_rule_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrule',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
