# Generated by Django 4.1.5 on 2023-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_alter_firewallrule_protocol_alter_nat_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='action',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('DROP', 'DROP'), ('REJECT', 'REJECT')], default='ACCEPT', max_length=10),
        ),
    ]
