# Generated by Django 4.1.5 on 2023-05-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_firewallrule_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
